### PR TITLE
Deadline 2  Group A: Fixed src(links) 

### PR DESCRIPTION
**Pull request by sikehish**
I have included the navigate/window.open methods related to learn more and more on events page and home page. Please review it. Also, I have included the Chinese translation for the remaining 2 events in the events page.
UPDATE: Made the events section responsive

### CODE REVIEW

**Comment by Labhk** [comment]
It's not mobile responsive

**Comment by Labhk** [comment]
Links are working👍

**Comment by sikehish** [comment]
@Labhk Working on make it more mobile friendly

**Comment by Labhk** [comment]
looks great

**Comment by RinSoftwareDeveloper** [comment]
Checked by Ethan
Merged 7/21/2023

**Pull request merged**
