### PR TITLE
Added the Learn more

### PR DESCRIPTION
**Pull request by AdamBures**
I have added the learn more for web pages.

### CODE REVIEW

**Comment by RinSoftwareDeveloper** [comment]
Checked by Ethan
Merged on 7/21/2023

**Comment by RinSoftwareDeveloper** [comment]
@AdamBures Please merge and resolve conflicts?

**Comment by AdamBures** [comment]
I will this is still work in progress.

**Comment by Labhk** [comment]
looks good

**Review by Labhk — APPROVED** [review]

**Review by RinSoftwareDeveloper — COMMENTED** [review]
set

**Pull request merged**
